name: apk_installer
description: A Flutter plugin for easy Android APK installation, compatible with Android API 19 and higher.
version: 1.0.0
homepage: https://github.com/ShadyCyan/apk_installer

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shadycyan.apk_installer
        pluginClass: ApkInstallerPlugin
